apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJrZW5uZHJpY2suamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImVXOXJaVzV1TnpkQVoyMWhhV3d1WTI5dE9sZHBaR0ZoWkVBM053PT0iCgkJfQoJfQp9Cg==
kind: Secret
metadata:
  name: jfrogauth
type: kubernetes.io/dockerconfigjson